/**
 * crypto/derive-keypair.ts — Deterministic BabyJubJub keypair derivation.
 *
 * Provides a single function that derives a BabyJub keypair from an arbitrary
 * byte payload (typically a wallet signature) via HKDF-SHA256. The result is
 * deterministic: the same input bytes + same context always produce the same
 * keypair, enabling **multi-device key recovery without on-chain storage**.
 *
 * ─── Why this matters ────────────────────────────────────────────────────────
 *
 * `generateBabyJubKeypair()` draws a fresh random scalar every call. This is
 * correct for ephemeral keys (e.g. one-time ECIES senders) but unsuitable for
 * a user's persistent MemoKey: the key is lost the instant the browser tab is
 * cleared or the user switches devices.
 *
 * The "sign-derive" pattern solves this without a backup phrase:
 *
 *   1. App prompts the user to sign a deterministic message with their wallet
 *      (e.g. EIP-191 personal_sign over a fixed string like "OpenJanus MemoKey v1").
 *   2. The 65-byte signature is passed to `deriveBabyJubKeypairFromBytes`.
 *   3. The same keypair is recovered on any device — as long as the user has
 *      access to the same wallet private key (hardware or software).
 *
 * This is exactly the same primitive that Phantom, Argent and Rabby use for
 * their non-custodial encrypted-messaging / stealth-address key trees: the
 * wallet's signing key acts as a root secret from which app-specific keys are
 * derived via HKDF without ever touching the signing key directly.
 *
 * ─── Key separation ──────────────────────────────────────────────────────────
 *
 * The `context` parameter is a domain-separation label fed into HKDF as the
 * "info" field. Separate values produce cryptographically independent scalars
 * from the same input bytes, so a single wallet signature can simultaneously
 * derive:
 *
 *   "openjanus/memokey/v1"   → the user's persistent memo-encryption key
 *   "openjanus/viewkey/v1"   → a read-only audit key (future)
 *   "openjanus/spendkey/v1"  → a spend-authorization key (future)
 *
 * without any scalar leaking information about any other.
 *
 * ─── HKDF construction ───────────────────────────────────────────────────────
 *
 *   IKM  = inputBytes (wallet signature, 64+ bytes recommended)
 *   salt = UTF-8("openjanus/derive-babyjub/v1")   ← hard-coded, versioned
 *   info = UTF-8(context)                          ← caller-supplied
 *   L    = 64 bytes
 *
 *   output_bigint = big-endian decode(HKDF(IKM, salt, info, L))
 *   scalar        = output_bigint mod BABYJUB_SUBGROUP_ORDER
 *   if scalar == 0: scalar = 1   ← astronomically unlikely; defensive guard
 *
 * The 64-byte output guarantees <2^-127 bias when reducing mod l ≈ 2^251.
 *
 * ─── Entropy requirements ────────────────────────────────────────────────────
 *
 * `inputBytes` MUST have sufficient entropy. Recommended sources:
 *
 *   - An EIP-191 wallet signature (65 bytes, r+s+v) — the wallet's ECDSA r/s
 *     values are uniformly random over a nonce fresh per signature.
 *   - A BIP-32 child private key (32 bytes, uniform).
 *   - Any 32+ byte CSPRNG output.
 *
 * DO NOT use low-entropy inputs (user passwords, short strings, block numbers).
 * DO NOT use the derived scalar directly for ECDSA — it lives on BabyJub, not secp256k1.
 *
 * ─── Thread safety ────────────────────────────────────────────────────────────
 *
 * This function is pure and stateless; concurrent calls are safe. The underlying
 * WebCrypto HKDF call is spec'd as non-extractable so the IKM bytes leave no
 * CryptoKey object behind.
 */

import type { BabyJubKeypair } from "./babyjub-keypair";
import { pubkeyFromPrivkey } from "./babyjub-keypair";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * BabyJubJub subgroup order `l`.
 *
 * This is the number of points in the prime-order subgroup generated by BASE8.
 * A valid BabyJub private scalar must lie in [1, l).
 *
 * Computed as: l = 2736030358979909402780800718157159386076813972158567259200215660948447373041
 * (matches circomlibjs + snarkjs constants; same value used in Hermez / Aztec circuits.)
 */
const BABYJUB_SUBGROUP_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n;

/** HKDF salt — versioned so future schemes can coexist without collision. */
const HKDF_SALT_BYTES = new TextEncoder().encode(
  "openjanus/derive-babyjub/v1"
);

/** Number of HKDF output bytes. 64B → 512-bit integer → bias < 2^-127 after mod l. */
const HKDF_OUTPUT_BYTES = 64;

// ---------------------------------------------------------------------------
// Internal helpers — WebCrypto HKDF (same pattern as encrypt-text.ts)
// ---------------------------------------------------------------------------

async function getCrypto(): Promise<Crypto> {
  if (
    typeof globalThis !== "undefined" &&
    (globalThis as { crypto?: Crypto }).crypto
  ) {
    return (globalThis as { crypto: Crypto }).crypto;
  }
  // Node <19 fallback (Node 18+ has webcrypto on globalThis).
  const nodeCrypto = (await import("crypto")) as unknown as {
    webcrypto: Crypto;
  };
  return nodeCrypto.webcrypto;
}

/**
 * Run HKDF-SHA256 over `ikm` with the versioned salt and caller-supplied info.
 * Returns `HKDF_OUTPUT_BYTES` (64) bytes of pseudorandom keying material.
 */
async function hkdfSha256(
  ikm: Uint8Array,
  info: Uint8Array
): Promise<Uint8Array> {
  const crypto = await getCrypto();

  const baseKey = await crypto.subtle.importKey(
    "raw",
    ikm as unknown as ArrayBuffer,
    "HKDF",
    false,
    ["deriveBits"]
  );

  const bits = await crypto.subtle.deriveBits(
    {
      name: "HKDF",
      hash: "SHA-256",
      salt: HKDF_SALT_BYTES as unknown as ArrayBuffer,
      info: info as unknown as ArrayBuffer,
    },
    baseKey,
    HKDF_OUTPUT_BYTES * 8 // length in bits
  );

  return new Uint8Array(bits);
}

/**
 * Decode a big-endian Uint8Array as an unsigned BigInt.
 */
function bigEndianToBigInt(bytes: Uint8Array): bigint {
  let result = 0n;
  for (const byte of bytes) {
    result = (result << 8n) | BigInt(byte);
  }
  return result;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Derive a deterministic BabyJubJub keypair from arbitrary secret bytes.
 *
 * Given the same `inputBytes` and `context`, this function always returns
 * the **same keypair** — making it suitable for "sign-in to recover" flows
 * where a wallet signature acts as the root secret.
 *
 * ### Typical usage
 *
 * ```typescript
 * // Prompt user to sign a fixed message with their wallet:
 * const sig = await wallet.signMessage("OpenJanus MemoKey v1");
 * const sigBytes = ethers.getBytes(sig); // 65-byte Uint8Array
 *
 * // Derive the same keypair on any device that holds the same wallet key:
 * const keypair = await deriveBabyJubKeypairFromBytes(sigBytes);
 *
 * // Store only keypair.pubkey on-chain; keep keypair.privkey in memory only.
 * ```
 *
 * ### Key separation
 *
 * Pass different `context` values to derive independent keys from the same
 * signature (e.g. `"openjanus/viewkey/v1"` vs `"openjanus/spendkey/v1"`).
 * The outputs are cryptographically independent — knowing one leaks nothing
 * about another.
 *
 * ### Entropy requirements
 *
 * `inputBytes` must carry adequate entropy. The recommended source is a fresh
 * wallet signature (EIP-191 personal_sign), which provides 256 bits of
 * ECDSA nonce randomness. Short strings, block numbers, or user-chosen
 * passwords are **not** suitable.
 *
 * Minimum length: 32 bytes. Typical wallet signatures are 65 bytes (r+s+v).
 * Longer inputs (e.g. concatenated signature + account address) are fine.
 *
 * ### Why this is safe
 *
 * - HKDF-SHA256 is a PRF: the derived scalar is indistinguishable from
 *   random to any adversary who does not know `inputBytes`.
 * - The 64-byte HKDF output gives a < 2^-127 statistical bias after
 *   reducing modulo the 251-bit BabyJub subgroup order.
 * - The versioned salt `"openjanus/derive-babyjub/v1"` domain-separates
 *   this derivation from all other HKDF usages in the SDK.
 *
 * @param inputBytes - Secret entropy source (wallet signature, seed, etc.).
 *                     Must be ≥ 32 bytes. Wallet signatures (65 B) are ideal.
 * @param context    - Domain-separation label for key separation.
 *                     Defaults to `"openjanus/memokey/v1"`.
 * @returns Deterministic BabyJubJub keypair `{ privkey, pubkey }`.
 *          The privkey is a scalar in [1, l); the pubkey is privkey × BASE8.
 */
export async function deriveBabyJubKeypairFromBytes(
  inputBytes: Uint8Array,
  context: string = "openjanus/memokey/v1"
): Promise<BabyJubKeypair> {
  if (inputBytes.length < 32) {
    throw new Error(
      "deriveBabyJubKeypairFromBytes: inputBytes must be at least 32 bytes " +
        `(got ${inputBytes.length}). Use a wallet signature (65 B) or CSPRNG output.`
    );
  }

  const infoBytes = new TextEncoder().encode(context);
  const derived = await hkdfSha256(inputBytes, infoBytes);

  // Reduce modulo subgroup order; guard the zero scalar.
  let scalar = bigEndianToBigInt(derived) % BABYJUB_SUBGROUP_ORDER;
  if (scalar === 0n) {
    // Probability ≈ 2^-251 — purely defensive.
    scalar = 1n;
  }

  const pubkey = await pubkeyFromPrivkey(scalar);
  return { privkey: scalar, pubkey };
}
