/**
 * utils/pi-b-swap.ts — EIP-197 Fp2 coordinate swap helper
 *
 * Critical transformation for Groth16 proofs submitted to EVM verifiers.
 *
 * BACKGROUND:
 *   snarkJS outputs pi_b in the form [[re0, im0], [re1, im1]] (re, im per BN254 Fp2 element).
 *   The EIP-197 ecPairing precompile (and Solidity verifiers generated by snarkjs) expect
 *   the coordinates in reversed (im, re) order: [[im0, re0], [im1, re1]].
 *
 *   Without this swap, verifyProof returns false for every valid proof — a silent
 *   correctness bug that's extremely hard to diagnose.
 *
 * REFERENCE:
 *   EIP-197: https://eips.ethereum.org/EIPS/eip-197
 *   snarkjs export calldata format: G2 in Fq2 with Fp2 coordinates reversed
 */

import type { SnarkJSProof, EVMProof, ProofUint256 } from "../types/proof";

/**
 * Apply the EIP-197 Fp2 coordinate swap to a snarkJS proof.
 *
 * snarkJS pi_b: [[b00, b01], [b10, b11]]   (re, im per element)
 * EIP-197:      [[b01, b00], [b11, b10]]   (im, re — swapped)
 *
 * @param proof  Raw snarkJS proof (pi_b in snarkjs order)
 * @returns      EVM-ready proof with pi_b Fp2 swap applied
 */
export function applyPiBSwap(proof: SnarkJSProof): EVMProof {
  return {
    pA: [BigInt(proof.pi_a[0]), BigInt(proof.pi_a[1])],
    pB: [
      [BigInt(proof.pi_b[0][1]), BigInt(proof.pi_b[0][0])],
      [BigInt(proof.pi_b[1][1]), BigInt(proof.pi_b[1][0])],
    ],
    pC: [BigInt(proof.pi_c[0]), BigInt(proof.pi_c[1])],
  };
}

/**
 * Flatten an EVMProof into a uint256[8] array for Solidity contract calls.
 * Order: [pA.x, pA.y, pB[0][0], pB[0][1], pB[1][0], pB[1][1], pC.x, pC.y]
 */
export function evmProofToUint256Array(
  evmProof: EVMProof
): [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] {
  return [
    evmProof.pA[0],
    evmProof.pA[1],
    evmProof.pB[0][0],
    evmProof.pB[0][1],
    evmProof.pB[1][0],
    evmProof.pB[1][1],
    evmProof.pC[0],
    evmProof.pC[1],
  ];
}

/**
 * Split a ProofUint256 (uint256[8]) back into separate pA, pB, pC components
 * for contract ABIs that take the proof split (not packed).
 *
 * wrapWithProof ABI: (nonce, commit[2], pA[2], pB[2][2], pC[2], ...)
 */
export function splitProof(proof: ProofUint256 | readonly [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint]): {
  pA: [bigint, bigint];
  pB: [[bigint, bigint], [bigint, bigint]];
  pC: [bigint, bigint];
} {
  return {
    pA: [proof[0], proof[1]],
    pB: [
      [proof[2], proof[3]],
      [proof[4], proof[5]],
    ],
    pC: [proof[6], proof[7]],
  };
}
